version: '3'
services:
  web:
    image: node:21-alpine3.17 # Use a imagem do Node.js
    working_dir: /app
    volumes:
      - ./:/app
    command: npm start
    ports:
      - "80:3333"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: urubu100
    ports:
      - "3306:3306"